"""empty message

Revision ID: 916e41b3eae3
Revises: 0566b7511019
Create Date: 2021-11-11 22:51:38.907746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916e41b3eae3'
down_revision = '0566b7511019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('token_fcm', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('token_fcm', 'user', ['token_fcm'], unique=False)
    # ### end Alembic commands ###
