"""empty message

Revision ID: efad592acbe1
Revises: ed6a61e03900
Create Date: 2021-11-17 16:08:07.118505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad592acbe1'
down_revision = 'ed6a61e03900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.Enum('user', 'oferta_laboral', 'necesidad_egresados', name='entities'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_type')
    # ### end Alembic commands ###
